name: cli_spinner
description: A small tool that allows to show a message with spinner to a user.
version: 1.0.0
# homepage: https://www.example.com

repository: https://github.com/DutchRican/cli_spinner

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  ansi_escapes: ^1.0.0
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
